language: python
sudo: false
python:
  - 2.6
  - 2.7_with_system_site_packages
env:
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=wx
addons:
  apt:
    packages:
    - pyhton-qt4-dev
    - python-qt4
    - python-qt4-gl
    - python-imaging
    - python-pip
    - python-wxtools
    - python-numpy
    - swig
    - ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install cython
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - coverage run -m nose.core -v chaco/tests
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coverage run -a -m nose.core -v chaco; fi
after_success:
  - pip install codecov
  - codecov
