language: python
python:
  - 2.7
  - 2.6
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
before_install:
  # On Python 2.7 we install PyQt4 and run the UI tests.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then source .travis_before_install; fi
  - sudo apt-get update
  - sudo apt-get install python-numpy swig

install:
  - pip install cython
  - pip install coveralls
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  # Running all tests in chaco/tests and chaco/tests2
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run -m nose.core -v chaco; fi
  # FIXME: tricky to install PyQt for version <= 2.6, only running chaco/tests
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run -m nose.core -v chaco/tests; fi
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls