language: python
python:
  - '2.7_with_system_site_packages'
  - 2.6
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy swig
  # Simlinks for PIL compilation
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libpng.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/
  - source .travis_before_install
install:
  - pip install cython
  - pip install coveralls
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - if [[ $TRAVIS_PYTHON_VERSION == *_with_system_site_packages ]]; then ETS_TOOLKIT='qt4' coverage run -p -m nose.core -v chaco; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *_with_system_site_packages ]]; then ETS_TOOLKIT='wx' coverage run -p -m nose.core -v chaco; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *_with_system_site_packages ]]; then coverage combine; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run -m nose.core -v chaco/tests; fi
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
